### ISSUE TITLE
Translation To Arabic did not work

### ISSUE THREAD

**Issue by justmejust** [aakvatech/PropMS#10]
what about the translation?
i installed Property Management Solution successfully to Erpnext but i faced problem with Arabic Translation .
the Erpnext App is just when you change your language all system become translated to your selected Language but most of Property Management Solution DocTypes Does not!!!
how this issue could be solved?
thank you

**Comment by aakvatech** [comment]
Send screenshot of problem

**Comment by aakvatech** [comment]
As per the discuss chat, the translation for specific words can be added to custom transalations using core frappe feature and it will thereafter appear.
